### ISSUE TITLE
segfaults with SPARTAN data on Debian 4.19.98-1 (2020-01-26) x86_64

### ISSUE THREAD

**Issue by StuartLittlefair** [schirmermischa/THELI#1]
Hi @schirmermischa 

Thanks for the work on THELI V3. It really is fantastic. I'm attempting to pre-process some SPARTAN data; up to background subtraction. Things seem to run smoothly but there is always a segmentation fault when I'm not looking. 

Is there any way of providing log output/debugging information to help you track down the issue?

**Comment by schirmermischa** [comment]
Hi Stuart,

yes, in the background subtraction module there is still an unresolved bug. It has to do with the openMP parallelization and some of the Qt5 C++ classes not being fully thread safe. I have fixed all of these issues, but this particular one remains. The solution should be simple: just run the background modeling with a single CPU (click on the "gears" symbol), and it should be fine.

Let me know how it goes!

**Comment by schirmermischa** [comment]
This is basically the main reason why the current version is still a beta-release...

**Comment by StuartLittlefair** [comment]
:( No joy unfortunately; segfaults are still occurring even with a single CPU, and it's not actually getting as far as background subtraction.

**Comment by schirmermischa** [comment]
So at which step does it happen then? Can you upload some raw FITS files for me to reproduce it? I haven't tested SPARTAN data yet with v3, perhaps it's just an issue with the raw FITS headers not being interpreted correctly.

**Comment by StuartLittlefair** [comment]
OK - it's failing on the process FLAT OFF/DARK step at the moment. I will upload a minimal dataset somewhere for you to try tomorrow.

**Comment by schirmermischa** [comment]
Hi Stuart. Can we continue this thread over email until it is resolved? More practical for me. You can reach me at schirmer[at]mpia.de

**Comment by schirmermischa** [comment]
Closed. The problem was that the SPARTAN data come in single FITS files (instead of a MEF FITS), requiring to be included in a dedicated code section.
